sonar.projectKey=tinalmeid_mlpulse_SRE
sonar.organization=tinalmeid
sonar.projectName=MLPulse SRE
sonar.projectVersion=0.2.0

# Código fonte
sonar.sources=app
sonar.tests=tests
sonar.language=py

# Cobertura
sonar.python.coverage.reportPaths=coverage.xml

# Exclusões
sonar.exclusions=**/__pycache__/**,**/.venv/**,**/models/**
